In [4]:
from gdmloader.constants import GCS_CASE_SOURCE
from gdmloader.source import SystemLoader
import gdm
gdm_loader = SystemLoader()
gdm_loader.add_source(GCS_CASE_SOURCE)
gdm_loader.show_sources()

┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃     Name ┃ URL                                     ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ gdm_data │ https://storage.googleapis.com/gdm_data │
└──────────┴─────────────────────────────────────────┘

In [5]:
from gdm.distribution import DistributionSystem
distribution_system: DistributionSystem = gdm_loader.load_dataset(system_type=DistributionSystem,
                                                                  source_name="gdm_data",
                                                                  dataset_name="p1rhs7_1247",)

In [6]:
distribution_system.info()

System
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Property             ┃ Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ System name          │       │
│ Data format version  │ 2.1.4 │
│ Components attached  │ 13370 │
│ Time Series attached │     0 │
│ Description          │       │
└──────────────────────┴───────┘

Component Information
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Type                             ┃ Count ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ DistributionBus                  │  2510 │
│ DistributionLoad                 │  1896 │
│ DistributionTransformer          │   503 │
│ DistributionTransformerEquipment │    10 │
│ DistributionVoltageSource        │     1 │
│ LoadEquipment                    │  1896 │
│ Location                         │  2510 │
│ MatrixImpedanceBranch            │  1841 │
│ MatrixImpedanceBranchEquipment   │    38 │
│ MatrixImpedanceFuse              │    81 │
│ MatrixImpedanceFuseEquipment     │     6 │
│ MatrixImpedanceSwitch            │    84 │
│ MatrixImpedanceSwitchEquipment   │    15 │
│ PhaseLoadEquipment               │  1948 │
│ PhaseVoltageSourceEquipment      │     3 │
│ TimeCurrentCurve                 │     1 │
│ VoltageLimitSet                  │     8 │
│ VoltageSourceEquipment           │     1 │
│ WindingEquipment                 │    18 │
└──────────────────────────────────┴───────┘

In [2]:
from gdm.distribution import CatalogSystem

catalog_system: CatalogSystem = gdm_loader.load_dataset(
    system_type=CatalogSystem,
    source_name="gdm_data",
    dataset_name="gdm_catalog",
)

In [3]:
catalog_system.info()

System
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Property             ┃ Value ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ System name          │       │
│ Data format version  │ 2.1.4 │
│ Components attached  │ 25879 │
│ Time Series attached │     0 │
│ Description          │       │
└──────────────────────┴───────┘

Component Information
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Type                             ┃ Count ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ BareConductorEquipment           │   578 │
│ CapacitorEquipment               │   382 │
│ ConcentricCableEquipment         │   364 │
│ Curve                            │  4324 │
│ DistributionTransformerEquipment │  3705 │
│ InverterEquipment                │  4324 │
│ PhaseCapacitorEquipment          │   468 │
│ SolarEquipment                   │  4324 │
│ WindingEquipment                 │  7410 │
└──────────────────────────────────┴───────┘

In [17]:
from gdm.distribution.equipment import DistributionTransformerEquipment
import pandas as pd

distribution_transformer_xfmr_in_range = [d for d in catalog_system.get_components(DistributionTransformerEquipment) if d.winding_reactances[0] >= 4 and d.winding_reactances[0] <= 5]
df = pd.DataFrame([d.__dict__ for d in distribution_transformer_xfmr_in_range])
df
# for d in catalog_system.get_components(DistributionTransformerEquipment):
#     df = pd.concat([df, pd.DataFrame([d.__dict__])], ignore_index=True)

# # Get unique reactance values
# unique_reactances = set()
# for d in catalog_system.get_components(DistributionTransformerEquipment):
#     unique_reactances.update(d.winding_reactances)
# # Convert the set to a sorted list
# unique_reactances = sorted(unique_reactances)
# print(unique_reactances)

,uuid,name,mounting,pct_no_load_loss,pct_full_load_loss,windings,coupling_sequences,winding_reactances,is_center_tapped
0,e8167d3e-33a3-4aab-82d7-152bcb61b083,3p_300kva_4160Y_208Y,TransformerMounting.POLE_MOUNT,0.466667,2.066667,[name='' resistance=1.035 is_grounded=False ra...,"[(0, 1)]",[4.0],False
1,fdf523f9-d42b-4850-8fa9-766472061326,3p_300kva_12470Y_208Y,TransformerMounting.POLE_MOUNT,0.466667,2.066667,[name='' resistance=1.035 is_grounded=False ra...,"[(0, 1)]",[4.0],False
2,060e451e-5222-4e2d-a21d-ecacb1d3a3e0,3p_300kva_13200Y_208Y,TransformerMounting.POLE_MOUNT,0.466667,2.066667,[name='' resistance=1.035 is_grounded=False ra...,"[(0, 1)]",[4.0],False
3,528f504f-d99d-486e-a7f5-28b03eebc3a3,3p_300kva_13800Y_208Y,TransformerMounting.POLE_MOUNT,0.466667,2.066667,[name='' resistance=1.035 is_grounded=False ra...,"[(0, 1)]",[4.0],False
4,c0bcd2ee-444a-4488-94ba-30df65518f9c,3p_300kva_24940Y_208Y,TransformerMounting.POLE_MOUNT,0.466667,2.066667,[name='' resistance=1.035 is_grounded=False ra...,"[(0, 1)]",[4.0],False
...,...,...,...,...,...,...,...,...,...
525,36021c09-bc74-444f-aca1-f9589fa23978,S2000_V34500_P3_F60,TransformerMounting.POLE_MOUNT,0.100000,1.000000,[name='' resistance=0.54 is_grounded=False rat...,"[(0, 1)]",[4.0],False
526,aaaab190-a288-4927-9403-4e293c68fb8a,S2000_V34500_P3_F60,TransformerMounting.POLE_MOUNT,0.100000,1.000000,[name='' resistance=0.54 is_grounded=False rat...,"[(0, 1)]",[4.0],False
527,9ada9e66-3182-4cbb-81b1-18ba8e11769d,S625_V34500_P3_F60,TransformerMounting.POLE_MOUNT,0.100000,1.000000,[name='' resistance=0.62 is_grounded=False rat...,"[(0, 1)]",[4.0],False
528,a81ec4bf-3b7b-4797-9c31-e2e6e651fc3c,S1250_V34500_P3_F60,TransformerMounting.POLE_MOUNT,0.100000,1.000000,[name='' resistance=0.525 is_grounded=False ra...,"[(0, 1)]",[4.0],False
529,82a601f0-025a-404a-ae22-e6daef399f8f,S2667_V34500_P3_F60,TransformerMounting.POLE_MOUNT,0.100000,1.000000,[name='' resistance=0.475 is_grounded=False ra...,"[(0, 1)]",[4.0],False

In [ ]:
from gdm.distribution.equipment import BareConductorEquipment, ConcentricCableEquipment
bare_conductors = list(catalog_system.get_components(BareConductorEquipment))
min(bare_conductors, key=lambda x: abs(x.ampacity.magnitude - 1200))

BareConductorEquipment(name='HEN/ACSS', conductor_diameter=<Quantity(0.883, 'inch')>, conductor_gmr=<Quantity(0.304, 'foot')>, ampacity=<Quantity(1200.0, 'ampere')>, ac_resistance=<Quantity(0.223872, 'ohm / meter')>, emergency_ampacity=<Quantity(1200.0, 'ampere')>, dc_resistance=<Quantity(0.181632, 'ohm / meter')>)

In [39]:
import pandas as pd
cables = list(catalog_system.get_components(BareConductorEquipment))
# min(cables, key=lambda x: abs(x.ampacity.magnitude - 1200))
cables_above_1500 = [c for c in cables if c.ampacity.magnitude >= 1500]

In [41]:
df = pd.DataFrame()
for cable in cables_above_1500:
    df = pd.concat([df, pd.DataFrame([cable.__dict__])], ignore_index=True)
df.head()

,uuid,name,conductor_diameter,conductor_gmr,ampacity,ac_resistance,emergency_ampacity,dc_resistance
0,7e832daf-c819-4650-913b-21e7b4dbc278,BLUEBIRD,1.762 inch,0.0588 foot,1623.0 ampere,0.05544 ohm / meter,1623.0 ampere,0.04224 ohm / meter
1,eb78921a-933f-4dc0-af7a-44ffb8715b77,KIWI,1.735 inch,0.057 foot,1607.0 ampere,0.055968000000000004 ohm / meter,1607.0 ampere,0.04224 ohm / meter
2,5e4c2efa-d4ad-4a97-adcd-c22256b86ecd,THRASHER,1.802 inch,0.06 foot,1673.0 ampere,0.05280000000000001 ohm / meter,1673.0 ampere,0.0396 ohm / meter
3,28bed351-9c8b-48b6-9869-bc68a5f6c85d,JOREA,1.88 inch,0.0621 foot,1751.0 ampere,0.049103999999999995 ohm / meter,1751.0 ampere,0.036432 ohm / meter
4,c4c164a5-c9e1-41e4-b749-9c87d4d5bae8,BLUEBIRD/TW,1.608 inch,0.0538 foot,1585.0 ampere,0.054912 ohm / meter,1585.0 ampere,0.04224 ohm / meter